function [trainedClassifier, validationAccuracy] = trainClassifier(trainingData)
% [trainedClassifier, validationAccuracy] = trainClassifier(trainingData)
% Returns a trained classifier and its accuracy. This code recreates the
% classification model trained in Classification Learner app. Use the
% generated code to automate training the same model with new data, or to
% learn how to programmatically train models.
%
%  Input:
%      trainingData: A table containing the same predictor and response
%       columns as those imported into the app.
%
%
%  Output:
%      trainedClassifier: A struct containing the trained classifier. The
%       struct contains various fields with information about the trained
%       classifier.
%
%      trainedClassifier.predictFcn: A function to make predictions on new
%       data.
%
%      validationAccuracy: A double representing the validation accuracy as
%       a percentage. In the app, the Models pane displays the validation
%       accuracy for each model.
%
% Use the code to train the model with new data. To retrain your
% classifier, call the function from the command line with your original
% data or new data as the input argument trainingData.
%
% For example, to retrain a classifier trained with the original data set
% T, enter:
%   [trainedClassifier, validationAccuracy] = trainClassifier(T)
%
% To make predictions with the returned 'trainedClassifier' on new data T2,
% use
%   [yfit,scores] = trainedClassifier.predictFcn(T2)
%
% T2 must be a table containing at least the same predictor columns as used
% during training. For details, enter:
%   trainedClassifier.HowToPredict

% Auto-generated by MATLAB on 06-Mar-2025 11:24:41


% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'FRM_1/acc_x_sigstats/ClearanceFactor', 'FRM_1/acc_x_sigstats/CrestFactor', 'FRM_1/acc_x_sigstats/ImpulseFactor', 'FRM_1/acc_x_sigstats/Kurtosis', 'FRM_1/acc_x_sigstats/Mean', 'FRM_1/acc_x_sigstats/PeakValue', 'FRM_1/acc_x_sigstats/RMS', 'FRM_1/acc_x_sigstats/ShapeFactor', 'FRM_1/acc_x_sigstats/Skewness', 'FRM_1/acc_x_sigstats/Std', 'FRM_1/acc_y_sigstats/ClearanceFactor', 'FRM_1/acc_y_sigstats/CrestFactor', 'FRM_1/acc_y_sigstats/ImpulseFactor', 'FRM_1/acc_y_sigstats/Kurtosis', 'FRM_1/acc_y_sigstats/Mean', 'FRM_1/acc_y_sigstats/PeakValue', 'FRM_1/acc_y_sigstats/RMS', 'FRM_1/acc_y_sigstats/ShapeFactor', 'FRM_1/acc_y_sigstats/Skewness', 'FRM_1/acc_y_sigstats/Std', 'FRM_1/acc_z_sigstats/ClearanceFactor', 'FRM_1/acc_z_sigstats/CrestFactor', 'FRM_1/acc_z_sigstats/ImpulseFactor', 'FRM_1/acc_z_sigstats/Kurtosis', 'FRM_1/acc_z_sigstats/Mean', 'FRM_1/acc_z_sigstats/PeakValue', 'FRM_1/acc_z_sigstats/RMS', 'FRM_1/acc_z_sigstats/ShapeFactor', 'FRM_1/acc_z_sigstats/Skewness', 'FRM_1/acc_z_sigstats/Std', 'FRM_1/gyr_x_sigstats/ClearanceFactor', 'FRM_1/gyr_x_sigstats/CrestFactor', 'FRM_1/gyr_x_sigstats/ImpulseFactor', 'FRM_1/gyr_x_sigstats/Kurtosis', 'FRM_1/gyr_x_sigstats/Mean', 'FRM_1/gyr_x_sigstats/PeakValue', 'FRM_1/gyr_x_sigstats/RMS', 'FRM_1/gyr_x_sigstats/ShapeFactor', 'FRM_1/gyr_x_sigstats/Skewness', 'FRM_1/gyr_x_sigstats/Std', 'FRM_1/gyr_y_sigstats/ClearanceFactor', 'FRM_1/gyr_y_sigstats/CrestFactor', 'FRM_1/gyr_y_sigstats/ImpulseFactor', 'FRM_1/gyr_y_sigstats/Kurtosis', 'FRM_1/gyr_y_sigstats/Mean', 'FRM_1/gyr_y_sigstats/PeakValue', 'FRM_1/gyr_y_sigstats/RMS', 'FRM_1/gyr_y_sigstats/ShapeFactor', 'FRM_1/gyr_y_sigstats/Skewness', 'FRM_1/gyr_y_sigstats/Std', 'FRM_1/gyr_z_sigstats/ClearanceFactor', 'FRM_1/gyr_z_sigstats/CrestFactor', 'FRM_1/gyr_z_sigstats/ImpulseFactor', 'FRM_1/gyr_z_sigstats/Kurtosis', 'FRM_1/gyr_z_sigstats/Mean', 'FRM_1/gyr_z_sigstats/PeakValue', 'FRM_1/gyr_z_sigstats/RMS', 'FRM_1/gyr_z_sigstats/ShapeFactor', 'FRM_1/gyr_z_sigstats/Skewness', 'FRM_1/gyr_z_sigstats/Std', 'FRM_1/pwm_1_sigstats/ClearanceFactor', 'FRM_1/pwm_1_sigstats/CrestFactor', 'FRM_1/pwm_1_sigstats/ImpulseFactor', 'FRM_1/pwm_1_sigstats/Kurtosis', 'FRM_1/pwm_1_sigstats/Mean', 'FRM_1/pwm_1_sigstats/PeakValue', 'FRM_1/pwm_1_sigstats/RMS', 'FRM_1/pwm_1_sigstats/ShapeFactor', 'FRM_1/pwm_1_sigstats/Skewness', 'FRM_1/pwm_1_sigstats/Std', 'FRM_1/pwm_2_sigstats/ClearanceFactor', 'FRM_1/pwm_2_sigstats/CrestFactor', 'FRM_1/pwm_2_sigstats/ImpulseFactor', 'FRM_1/pwm_2_sigstats/Kurtosis', 'FRM_1/pwm_2_sigstats/Mean', 'FRM_1/pwm_2_sigstats/PeakValue', 'FRM_1/pwm_2_sigstats/RMS', 'FRM_1/pwm_2_sigstats/ShapeFactor', 'FRM_1/pwm_2_sigstats/Skewness', 'FRM_1/pwm_2_sigstats/Std', 'FRM_1/pwm_3_sigstats/ClearanceFactor', 'FRM_1/pwm_3_sigstats/CrestFactor', 'FRM_1/pwm_3_sigstats/ImpulseFactor', 'FRM_1/pwm_3_sigstats/Kurtosis', 'FRM_1/pwm_3_sigstats/Mean', 'FRM_1/pwm_3_sigstats/PeakValue', 'FRM_1/pwm_3_sigstats/RMS', 'FRM_1/pwm_3_sigstats/ShapeFactor', 'FRM_1/pwm_3_sigstats/Skewness', 'FRM_1/pwm_3_sigstats/Std', 'FRM_1/pwm_4_sigstats/ClearanceFactor', 'FRM_1/pwm_4_sigstats/CrestFactor', 'FRM_1/pwm_4_sigstats/ImpulseFactor', 'FRM_1/pwm_4_sigstats/Kurtosis', 'FRM_1/pwm_4_sigstats/Mean', 'FRM_1/pwm_4_sigstats/PeakValue', 'FRM_1/pwm_4_sigstats/RMS', 'FRM_1/pwm_4_sigstats/ShapeFactor', 'FRM_1/pwm_4_sigstats/Skewness', 'FRM_1/pwm_4_sigstats/Std', 'FRM_1/pwm_5_sigstats/ClearanceFactor', 'FRM_1/pwm_5_sigstats/CrestFactor', 'FRM_1/pwm_5_sigstats/ImpulseFactor', 'FRM_1/pwm_5_sigstats/Kurtosis', 'FRM_1/pwm_5_sigstats/Mean', 'FRM_1/pwm_5_sigstats/PeakValue', 'FRM_1/pwm_5_sigstats/RMS', 'FRM_1/pwm_5_sigstats/ShapeFactor', 'FRM_1/pwm_5_sigstats/Skewness', 'FRM_1/pwm_5_sigstats/Std', 'FRM_1/pwm_6_sigstats/ClearanceFactor', 'FRM_1/pwm_6_sigstats/CrestFactor', 'FRM_1/pwm_6_sigstats/ImpulseFactor', 'FRM_1/pwm_6_sigstats/Kurtosis', 'FRM_1/pwm_6_sigstats/Mean', 'FRM_1/pwm_6_sigstats/PeakValue', 'FRM_1/pwm_6_sigstats/RMS', 'FRM_1/pwm_6_sigstats/ShapeFactor', 'FRM_1/pwm_6_sigstats/Skewness', 'FRM_1/pwm_6_sigstats/Std', 'FRM_1/roll_sigstats/ClearanceFactor', 'FRM_1/roll_sigstats/CrestFactor', 'FRM_1/roll_sigstats/ImpulseFactor', 'FRM_1/roll_sigstats/Kurtosis', 'FRM_1/roll_sigstats/Mean', 'FRM_1/roll_sigstats/PeakValue', 'FRM_1/roll_sigstats/RMS', 'FRM_1/roll_sigstats/ShapeFactor', 'FRM_1/roll_sigstats/Skewness', 'FRM_1/roll_sigstats/Std', 'FRM_1/pitch_sigstats/ClearanceFactor', 'FRM_1/pitch_sigstats/CrestFactor', 'FRM_1/pitch_sigstats/ImpulseFactor', 'FRM_1/pitch_sigstats/Kurtosis', 'FRM_1/pitch_sigstats/Mean', 'FRM_1/pitch_sigstats/PeakValue', 'FRM_1/pitch_sigstats/RMS', 'FRM_1/pitch_sigstats/ShapeFactor', 'FRM_1/pitch_sigstats/Skewness', 'FRM_1/pitch_sigstats/Std', 'FRM_1/yaw_sigstats/ClearanceFactor', 'FRM_1/yaw_sigstats/CrestFactor', 'FRM_1/yaw_sigstats/ImpulseFactor', 'FRM_1/yaw_sigstats/Kurtosis', 'FRM_1/yaw_sigstats/Mean', 'FRM_1/yaw_sigstats/PeakValue', 'FRM_1/yaw_sigstats/RMS', 'FRM_1/yaw_sigstats/ShapeFactor', 'FRM_1/yaw_sigstats/Skewness', 'FRM_1/yaw_sigstats/Std', 'FRM_1/roll_des_sigstats/ClearanceFactor', 'FRM_1/roll_des_sigstats/CrestFactor', 'FRM_1/roll_des_sigstats/ImpulseFactor', 'FRM_1/roll_des_sigstats/Kurtosis', 'FRM_1/roll_des_sigstats/Mean', 'FRM_1/roll_des_sigstats/PeakValue', 'FRM_1/roll_des_sigstats/RMS', 'FRM_1/roll_des_sigstats/ShapeFactor', 'FRM_1/roll_des_sigstats/Skewness', 'FRM_1/roll_des_sigstats/Std', 'FRM_1/pitch_des_sigstats/ClearanceFactor', 'FRM_1/pitch_des_sigstats/CrestFactor', 'FRM_1/pitch_des_sigstats/ImpulseFactor', 'FRM_1/pitch_des_sigstats/Kurtosis', 'FRM_1/pitch_des_sigstats/Mean', 'FRM_1/pitch_des_sigstats/PeakValue', 'FRM_1/pitch_des_sigstats/RMS', 'FRM_1/pitch_des_sigstats/ShapeFactor', 'FRM_1/pitch_des_sigstats/Skewness', 'FRM_1/pitch_des_sigstats/Std', 'FRM_1/yaw_des_sigstats/ClearanceFactor', 'FRM_1/yaw_des_sigstats/CrestFactor', 'FRM_1/yaw_des_sigstats/ImpulseFactor', 'FRM_1/yaw_des_sigstats/Kurtosis', 'FRM_1/yaw_des_sigstats/Mean', 'FRM_1/yaw_des_sigstats/PeakValue', 'FRM_1/yaw_des_sigstats/RMS', 'FRM_1/yaw_des_sigstats/ShapeFactor', 'FRM_1/yaw_des_sigstats/Skewness', 'FRM_1/yaw_des_sigstats/Std', 'FRM_1/vibe_x_sigstats/ClearanceFactor', 'FRM_1/vibe_x_sigstats/CrestFactor', 'FRM_1/vibe_x_sigstats/ImpulseFactor', 'FRM_1/vibe_x_sigstats/Kurtosis', 'FRM_1/vibe_x_sigstats/Mean', 'FRM_1/vibe_x_sigstats/PeakValue', 'FRM_1/vibe_x_sigstats/RMS', 'FRM_1/vibe_x_sigstats/ShapeFactor', 'FRM_1/vibe_x_sigstats/Skewness', 'FRM_1/vibe_x_sigstats/Std', 'FRM_1/vibe_y_sigstats/ClearanceFactor', 'FRM_1/vibe_y_sigstats/CrestFactor', 'FRM_1/vibe_y_sigstats/ImpulseFactor', 'FRM_1/vibe_y_sigstats/Kurtosis', 'FRM_1/vibe_y_sigstats/Mean', 'FRM_1/vibe_y_sigstats/PeakValue', 'FRM_1/vibe_y_sigstats/RMS', 'FRM_1/vibe_y_sigstats/ShapeFactor', 'FRM_1/vibe_y_sigstats/Skewness', 'FRM_1/vibe_y_sigstats/Std', 'FRM_1/vibe_z_sigstats/ClearanceFactor', 'FRM_1/vibe_z_sigstats/CrestFactor', 'FRM_1/vibe_z_sigstats/ImpulseFactor', 'FRM_1/vibe_z_sigstats/Kurtosis', 'FRM_1/vibe_z_sigstats/Mean', 'FRM_1/vibe_z_sigstats/PeakValue', 'FRM_1/vibe_z_sigstats/RMS', 'FRM_1/vibe_z_sigstats/ShapeFactor', 'FRM_1/vibe_z_sigstats/Skewness', 'FRM_1/vibe_z_sigstats/Std', 'FRM_1/acc_x_ps_spec/PeakAmp1', 'FRM_1/acc_x_ps_spec/PeakFreq1', 'FRM_1/acc_x_ps_spec/BandPower', 'FRM_1/acc_y_ps_spec/PeakAmp1', 'FRM_1/acc_y_ps_spec/PeakFreq1', 'FRM_1/acc_y_ps_spec/BandPower', 'FRM_1/acc_z_ps_spec/BandPower', 'FRM_1/gyr_x_ps_spec/PeakAmp1', 'FRM_1/gyr_x_ps_spec/PeakFreq1', 'FRM_1/gyr_x_ps_spec/BandPower', 'FRM_1/gyr_y_ps_spec/PeakAmp1', 'FRM_1/gyr_y_ps_spec/PeakFreq1', 'FRM_1/gyr_y_ps_spec/BandPower', 'FRM_1/gyr_z_ps_spec/BandPower', 'FRM_1/pwm_1_ps_spec/BandPower', 'FRM_1/pwm_2_ps_spec/BandPower', 'FRM_1/pwm_3_ps_spec/BandPower', 'FRM_1/pwm_4_ps_spec/BandPower', 'FRM_1/pwm_5_ps_spec/BandPower', 'FRM_1/pwm_6_ps_spec/BandPower', 'FRM_1/roll_ps_spec/BandPower', 'FRM_1/pitch_ps_spec/BandPower', 'FRM_1/yaw_ps_spec/BandPower', 'FRM_1/roll_des_ps_spec/PeakAmp1', 'FRM_1/roll_des_ps_spec/PeakFreq1', 'FRM_1/roll_des_ps_spec/BandPower', 'FRM_1/pitch_des_ps_spec/PeakAmp1', 'FRM_1/pitch_des_ps_spec/PeakFreq1', 'FRM_1/pitch_des_ps_spec/BandPower', 'FRM_1/yaw_des_ps_spec/BandPower', 'FRM_1/vibe_x_ps_spec/BandPower', 'FRM_1/vibe_y_ps_spec/BandPower', 'FRM_1/vibe_z_ps_spec/BandPower'};
predictors = inputTable(:, predictorNames);
response = inputTable.faultCode_binary;
isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];
classNames = categorical({'0'; '1'});

% Feature Ranking and Selection
% Replace Inf/-Inf values with NaN to prepare data for normalization
predictors = standardizeMissing(predictors, {Inf, -Inf});
% Normalize data for feature ranking
predictorMatrix = normalize(predictors, "DataVariable", ~isCategoricalPredictor);
newPredictorMatrix = zeros(size(predictorMatrix));
for i = 1:size(predictorMatrix, 2)
    if isCategoricalPredictor(i)
        newPredictorMatrix(:,i) = grp2idx(predictorMatrix{:,i});
    else
        newPredictorMatrix(:,i) = predictorMatrix{:,i};
    end
end
predictorMatrix = newPredictorMatrix;
responseVector = grp2idx(response);

% Rank features using ANOVA algorithm
for i = 1:size(predictorMatrix, 2)
    pValues(i) = anova1(...
        predictorMatrix(:,i), ...
        responseVector, ...
        'off');
end
[~,featureIndex] = sort(-log(pValues), 'descend');
numFeaturesToKeep = 50;
includedPredictorNames = predictors.Properties.VariableNames(featureIndex(1:numFeaturesToKeep));
predictors = predictors(:,includedPredictorNames);
isCategoricalPredictor = isCategoricalPredictor(featureIndex(1:numFeaturesToKeep));

% Train a classifier
% This code specifies all the classifier options and trains the classifier.
template = templateTree(...
    'MaxNumSplits', 20, ...
    'NumVariablesToSample', 'all');
classificationEnsemble = fitcensemble(...
    predictors, ...
    response, ...
    'Method', 'AdaBoostM1', ...
    'NumLearningCycles', 30, ...
    'Learners', template, ...
    'LearnRate', 0.1, ...
    'ClassNames', classNames);

% Create the result struct with predict function
predictorExtractionFcn = @(t) t(:, predictorNames);
featureSelectionFcn = @(x) x(:,includedPredictorNames);
ensemblePredictFcn = @(x) predict(classificationEnsemble, x);
trainedClassifier.predictFcn = @(x) ensemblePredictFcn(featureSelectionFcn(predictorExtractionFcn(x)));

% Add additional fields to the result struct
trainedClassifier.RequiredVariables = {'FRM_1/acc_x_sigstats/ClearanceFactor', 'FRM_1/acc_x_sigstats/CrestFactor', 'FRM_1/acc_x_sigstats/ImpulseFactor', 'FRM_1/acc_x_sigstats/Kurtosis', 'FRM_1/acc_x_sigstats/Mean', 'FRM_1/acc_x_sigstats/PeakValue', 'FRM_1/acc_x_sigstats/RMS', 'FRM_1/acc_x_sigstats/ShapeFactor', 'FRM_1/acc_x_sigstats/Skewness', 'FRM_1/acc_x_sigstats/Std', 'FRM_1/acc_y_sigstats/ClearanceFactor', 'FRM_1/acc_y_sigstats/CrestFactor', 'FRM_1/acc_y_sigstats/ImpulseFactor', 'FRM_1/acc_y_sigstats/Kurtosis', 'FRM_1/acc_y_sigstats/Mean', 'FRM_1/acc_y_sigstats/PeakValue', 'FRM_1/acc_y_sigstats/RMS', 'FRM_1/acc_y_sigstats/ShapeFactor', 'FRM_1/acc_y_sigstats/Skewness', 'FRM_1/acc_y_sigstats/Std', 'FRM_1/acc_z_sigstats/ClearanceFactor', 'FRM_1/acc_z_sigstats/CrestFactor', 'FRM_1/acc_z_sigstats/ImpulseFactor', 'FRM_1/acc_z_sigstats/Kurtosis', 'FRM_1/acc_z_sigstats/Mean', 'FRM_1/acc_z_sigstats/PeakValue', 'FRM_1/acc_z_sigstats/RMS', 'FRM_1/acc_z_sigstats/ShapeFactor', 'FRM_1/acc_z_sigstats/Skewness', 'FRM_1/acc_z_sigstats/Std', 'FRM_1/gyr_x_sigstats/ClearanceFactor', 'FRM_1/gyr_x_sigstats/CrestFactor', 'FRM_1/gyr_x_sigstats/ImpulseFactor', 'FRM_1/gyr_x_sigstats/Kurtosis', 'FRM_1/gyr_x_sigstats/Mean', 'FRM_1/gyr_x_sigstats/PeakValue', 'FRM_1/gyr_x_sigstats/RMS', 'FRM_1/gyr_x_sigstats/ShapeFactor', 'FRM_1/gyr_x_sigstats/Skewness', 'FRM_1/gyr_x_sigstats/Std', 'FRM_1/gyr_y_sigstats/ClearanceFactor', 'FRM_1/gyr_y_sigstats/CrestFactor', 'FRM_1/gyr_y_sigstats/ImpulseFactor', 'FRM_1/gyr_y_sigstats/Kurtosis', 'FRM_1/gyr_y_sigstats/Mean', 'FRM_1/gyr_y_sigstats/PeakValue', 'FRM_1/gyr_y_sigstats/RMS', 'FRM_1/gyr_y_sigstats/ShapeFactor', 'FRM_1/gyr_y_sigstats/Skewness', 'FRM_1/gyr_y_sigstats/Std', 'FRM_1/gyr_z_sigstats/ClearanceFactor', 'FRM_1/gyr_z_sigstats/CrestFactor', 'FRM_1/gyr_z_sigstats/ImpulseFactor', 'FRM_1/gyr_z_sigstats/Kurtosis', 'FRM_1/gyr_z_sigstats/Mean', 'FRM_1/gyr_z_sigstats/PeakValue', 'FRM_1/gyr_z_sigstats/RMS', 'FRM_1/gyr_z_sigstats/ShapeFactor', 'FRM_1/gyr_z_sigstats/Skewness', 'FRM_1/gyr_z_sigstats/Std', 'FRM_1/pwm_1_sigstats/ClearanceFactor', 'FRM_1/pwm_1_sigstats/CrestFactor', 'FRM_1/pwm_1_sigstats/ImpulseFactor', 'FRM_1/pwm_1_sigstats/Kurtosis', 'FRM_1/pwm_1_sigstats/Mean', 'FRM_1/pwm_1_sigstats/PeakValue', 'FRM_1/pwm_1_sigstats/RMS', 'FRM_1/pwm_1_sigstats/ShapeFactor', 'FRM_1/pwm_1_sigstats/Skewness', 'FRM_1/pwm_1_sigstats/Std', 'FRM_1/pwm_2_sigstats/ClearanceFactor', 'FRM_1/pwm_2_sigstats/CrestFactor', 'FRM_1/pwm_2_sigstats/ImpulseFactor', 'FRM_1/pwm_2_sigstats/Kurtosis', 'FRM_1/pwm_2_sigstats/Mean', 'FRM_1/pwm_2_sigstats/PeakValue', 'FRM_1/pwm_2_sigstats/RMS', 'FRM_1/pwm_2_sigstats/ShapeFactor', 'FRM_1/pwm_2_sigstats/Skewness', 'FRM_1/pwm_2_sigstats/Std', 'FRM_1/pwm_3_sigstats/ClearanceFactor', 'FRM_1/pwm_3_sigstats/CrestFactor', 'FRM_1/pwm_3_sigstats/ImpulseFactor', 'FRM_1/pwm_3_sigstats/Kurtosis', 'FRM_1/pwm_3_sigstats/Mean', 'FRM_1/pwm_3_sigstats/PeakValue', 'FRM_1/pwm_3_sigstats/RMS', 'FRM_1/pwm_3_sigstats/ShapeFactor', 'FRM_1/pwm_3_sigstats/Skewness', 'FRM_1/pwm_3_sigstats/Std', 'FRM_1/pwm_4_sigstats/ClearanceFactor', 'FRM_1/pwm_4_sigstats/CrestFactor', 'FRM_1/pwm_4_sigstats/ImpulseFactor', 'FRM_1/pwm_4_sigstats/Kurtosis', 'FRM_1/pwm_4_sigstats/Mean', 'FRM_1/pwm_4_sigstats/PeakValue', 'FRM_1/pwm_4_sigstats/RMS', 'FRM_1/pwm_4_sigstats/ShapeFactor', 'FRM_1/pwm_4_sigstats/Skewness', 'FRM_1/pwm_4_sigstats/Std', 'FRM_1/pwm_5_sigstats/ClearanceFactor', 'FRM_1/pwm_5_sigstats/CrestFactor', 'FRM_1/pwm_5_sigstats/ImpulseFactor', 'FRM_1/pwm_5_sigstats/Kurtosis', 'FRM_1/pwm_5_sigstats/Mean', 'FRM_1/pwm_5_sigstats/PeakValue', 'FRM_1/pwm_5_sigstats/RMS', 'FRM_1/pwm_5_sigstats/ShapeFactor', 'FRM_1/pwm_5_sigstats/Skewness', 'FRM_1/pwm_5_sigstats/Std', 'FRM_1/pwm_6_sigstats/ClearanceFactor', 'FRM_1/pwm_6_sigstats/CrestFactor', 'FRM_1/pwm_6_sigstats/ImpulseFactor', 'FRM_1/pwm_6_sigstats/Kurtosis', 'FRM_1/pwm_6_sigstats/Mean', 'FRM_1/pwm_6_sigstats/PeakValue', 'FRM_1/pwm_6_sigstats/RMS', 'FRM_1/pwm_6_sigstats/ShapeFactor', 'FRM_1/pwm_6_sigstats/Skewness', 'FRM_1/pwm_6_sigstats/Std', 'FRM_1/roll_sigstats/ClearanceFactor', 'FRM_1/roll_sigstats/CrestFactor', 'FRM_1/roll_sigstats/ImpulseFactor', 'FRM_1/roll_sigstats/Kurtosis', 'FRM_1/roll_sigstats/Mean', 'FRM_1/roll_sigstats/PeakValue', 'FRM_1/roll_sigstats/RMS', 'FRM_1/roll_sigstats/ShapeFactor', 'FRM_1/roll_sigstats/Skewness', 'FRM_1/roll_sigstats/Std', 'FRM_1/pitch_sigstats/ClearanceFactor', 'FRM_1/pitch_sigstats/CrestFactor', 'FRM_1/pitch_sigstats/ImpulseFactor', 'FRM_1/pitch_sigstats/Kurtosis', 'FRM_1/pitch_sigstats/Mean', 'FRM_1/pitch_sigstats/PeakValue', 'FRM_1/pitch_sigstats/RMS', 'FRM_1/pitch_sigstats/ShapeFactor', 'FRM_1/pitch_sigstats/Skewness', 'FRM_1/pitch_sigstats/Std', 'FRM_1/yaw_sigstats/ClearanceFactor', 'FRM_1/yaw_sigstats/CrestFactor', 'FRM_1/yaw_sigstats/ImpulseFactor', 'FRM_1/yaw_sigstats/Kurtosis', 'FRM_1/yaw_sigstats/Mean', 'FRM_1/yaw_sigstats/PeakValue', 'FRM_1/yaw_sigstats/RMS', 'FRM_1/yaw_sigstats/ShapeFactor', 'FRM_1/yaw_sigstats/Skewness', 'FRM_1/yaw_sigstats/Std', 'FRM_1/roll_des_sigstats/ClearanceFactor', 'FRM_1/roll_des_sigstats/CrestFactor', 'FRM_1/roll_des_sigstats/ImpulseFactor', 'FRM_1/roll_des_sigstats/Kurtosis', 'FRM_1/roll_des_sigstats/Mean', 'FRM_1/roll_des_sigstats/PeakValue', 'FRM_1/roll_des_sigstats/RMS', 'FRM_1/roll_des_sigstats/ShapeFactor', 'FRM_1/roll_des_sigstats/Skewness', 'FRM_1/roll_des_sigstats/Std', 'FRM_1/pitch_des_sigstats/ClearanceFactor', 'FRM_1/pitch_des_sigstats/CrestFactor', 'FRM_1/pitch_des_sigstats/ImpulseFactor', 'FRM_1/pitch_des_sigstats/Kurtosis', 'FRM_1/pitch_des_sigstats/Mean', 'FRM_1/pitch_des_sigstats/PeakValue', 'FRM_1/pitch_des_sigstats/RMS', 'FRM_1/pitch_des_sigstats/ShapeFactor', 'FRM_1/pitch_des_sigstats/Skewness', 'FRM_1/pitch_des_sigstats/Std', 'FRM_1/yaw_des_sigstats/ClearanceFactor', 'FRM_1/yaw_des_sigstats/CrestFactor', 'FRM_1/yaw_des_sigstats/ImpulseFactor', 'FRM_1/yaw_des_sigstats/Kurtosis', 'FRM_1/yaw_des_sigstats/Mean', 'FRM_1/yaw_des_sigstats/PeakValue', 'FRM_1/yaw_des_sigstats/RMS', 'FRM_1/yaw_des_sigstats/ShapeFactor', 'FRM_1/yaw_des_sigstats/Skewness', 'FRM_1/yaw_des_sigstats/Std', 'FRM_1/vibe_x_sigstats/ClearanceFactor', 'FRM_1/vibe_x_sigstats/CrestFactor', 'FRM_1/vibe_x_sigstats/ImpulseFactor', 'FRM_1/vibe_x_sigstats/Kurtosis', 'FRM_1/vibe_x_sigstats/Mean', 'FRM_1/vibe_x_sigstats/PeakValue', 'FRM_1/vibe_x_sigstats/RMS', 'FRM_1/vibe_x_sigstats/ShapeFactor', 'FRM_1/vibe_x_sigstats/Skewness', 'FRM_1/vibe_x_sigstats/Std', 'FRM_1/vibe_y_sigstats/ClearanceFactor', 'FRM_1/vibe_y_sigstats/CrestFactor', 'FRM_1/vibe_y_sigstats/ImpulseFactor', 'FRM_1/vibe_y_sigstats/Kurtosis', 'FRM_1/vibe_y_sigstats/Mean', 'FRM_1/vibe_y_sigstats/PeakValue', 'FRM_1/vibe_y_sigstats/RMS', 'FRM_1/vibe_y_sigstats/ShapeFactor', 'FRM_1/vibe_y_sigstats/Skewness', 'FRM_1/vibe_y_sigstats/Std', 'FRM_1/vibe_z_sigstats/ClearanceFactor', 'FRM_1/vibe_z_sigstats/CrestFactor', 'FRM_1/vibe_z_sigstats/ImpulseFactor', 'FRM_1/vibe_z_sigstats/Kurtosis', 'FRM_1/vibe_z_sigstats/Mean', 'FRM_1/vibe_z_sigstats/PeakValue', 'FRM_1/vibe_z_sigstats/RMS', 'FRM_1/vibe_z_sigstats/ShapeFactor', 'FRM_1/vibe_z_sigstats/Skewness', 'FRM_1/vibe_z_sigstats/Std', 'FRM_1/acc_x_ps_spec/PeakAmp1', 'FRM_1/acc_x_ps_spec/PeakFreq1', 'FRM_1/acc_x_ps_spec/BandPower', 'FRM_1/acc_y_ps_spec/PeakAmp1', 'FRM_1/acc_y_ps_spec/PeakFreq1', 'FRM_1/acc_y_ps_spec/BandPower', 'FRM_1/acc_z_ps_spec/BandPower', 'FRM_1/gyr_x_ps_spec/PeakAmp1', 'FRM_1/gyr_x_ps_spec/PeakFreq1', 'FRM_1/gyr_x_ps_spec/BandPower', 'FRM_1/gyr_y_ps_spec/PeakAmp1', 'FRM_1/gyr_y_ps_spec/PeakFreq1', 'FRM_1/gyr_y_ps_spec/BandPower', 'FRM_1/gyr_z_ps_spec/BandPower', 'FRM_1/pwm_1_ps_spec/BandPower', 'FRM_1/pwm_2_ps_spec/BandPower', 'FRM_1/pwm_3_ps_spec/BandPower', 'FRM_1/pwm_4_ps_spec/BandPower', 'FRM_1/pwm_5_ps_spec/BandPower', 'FRM_1/pwm_6_ps_spec/BandPower', 'FRM_1/roll_ps_spec/BandPower', 'FRM_1/pitch_ps_spec/BandPower', 'FRM_1/yaw_ps_spec/BandPower', 'FRM_1/roll_des_ps_spec/PeakAmp1', 'FRM_1/roll_des_ps_spec/PeakFreq1', 'FRM_1/roll_des_ps_spec/BandPower', 'FRM_1/pitch_des_ps_spec/PeakAmp1', 'FRM_1/pitch_des_ps_spec/PeakFreq1', 'FRM_1/pitch_des_ps_spec/BandPower', 'FRM_1/yaw_des_ps_spec/BandPower', 'FRM_1/vibe_x_ps_spec/BandPower', 'FRM_1/vibe_y_ps_spec/BandPower', 'FRM_1/vibe_z_ps_spec/BandPower'};
trainedClassifier.ClassificationEnsemble = classificationEnsemble;
trainedClassifier.About = 'This struct is a trained model exported from Classification Learner R2024b.';
trainedClassifier.HowToPredict = sprintf('To make predictions on a new table, T, use: \n  [yfit,scores] = c.predictFcn(T) \nreplace ''c'' with the name of the variable that is this struct, e.g. ''trainedModel''. \n \nThe table, T, must contain the variables returned by: \n  c.RequiredVariables \nVariable formats (e.g. matrix/vector, datatype) must match the original training data. \nAdditional variables are ignored. \n \nFor more information, see <a href="matlab:helpview(fullfile(docroot, ''stats'', ''stats.map''), ''appclassification_exportmodeltoworkspace'')">How to predict using an exported model</a>.');

% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'FRM_1/acc_x_sigstats/ClearanceFactor', 'FRM_1/acc_x_sigstats/CrestFactor', 'FRM_1/acc_x_sigstats/ImpulseFactor', 'FRM_1/acc_x_sigstats/Kurtosis', 'FRM_1/acc_x_sigstats/Mean', 'FRM_1/acc_x_sigstats/PeakValue', 'FRM_1/acc_x_sigstats/RMS', 'FRM_1/acc_x_sigstats/ShapeFactor', 'FRM_1/acc_x_sigstats/Skewness', 'FRM_1/acc_x_sigstats/Std', 'FRM_1/acc_y_sigstats/ClearanceFactor', 'FRM_1/acc_y_sigstats/CrestFactor', 'FRM_1/acc_y_sigstats/ImpulseFactor', 'FRM_1/acc_y_sigstats/Kurtosis', 'FRM_1/acc_y_sigstats/Mean', 'FRM_1/acc_y_sigstats/PeakValue', 'FRM_1/acc_y_sigstats/RMS', 'FRM_1/acc_y_sigstats/ShapeFactor', 'FRM_1/acc_y_sigstats/Skewness', 'FRM_1/acc_y_sigstats/Std', 'FRM_1/acc_z_sigstats/ClearanceFactor', 'FRM_1/acc_z_sigstats/CrestFactor', 'FRM_1/acc_z_sigstats/ImpulseFactor', 'FRM_1/acc_z_sigstats/Kurtosis', 'FRM_1/acc_z_sigstats/Mean', 'FRM_1/acc_z_sigstats/PeakValue', 'FRM_1/acc_z_sigstats/RMS', 'FRM_1/acc_z_sigstats/ShapeFactor', 'FRM_1/acc_z_sigstats/Skewness', 'FRM_1/acc_z_sigstats/Std', 'FRM_1/gyr_x_sigstats/ClearanceFactor', 'FRM_1/gyr_x_sigstats/CrestFactor', 'FRM_1/gyr_x_sigstats/ImpulseFactor', 'FRM_1/gyr_x_sigstats/Kurtosis', 'FRM_1/gyr_x_sigstats/Mean', 'FRM_1/gyr_x_sigstats/PeakValue', 'FRM_1/gyr_x_sigstats/RMS', 'FRM_1/gyr_x_sigstats/ShapeFactor', 'FRM_1/gyr_x_sigstats/Skewness', 'FRM_1/gyr_x_sigstats/Std', 'FRM_1/gyr_y_sigstats/ClearanceFactor', 'FRM_1/gyr_y_sigstats/CrestFactor', 'FRM_1/gyr_y_sigstats/ImpulseFactor', 'FRM_1/gyr_y_sigstats/Kurtosis', 'FRM_1/gyr_y_sigstats/Mean', 'FRM_1/gyr_y_sigstats/PeakValue', 'FRM_1/gyr_y_sigstats/RMS', 'FRM_1/gyr_y_sigstats/ShapeFactor', 'FRM_1/gyr_y_sigstats/Skewness', 'FRM_1/gyr_y_sigstats/Std', 'FRM_1/gyr_z_sigstats/ClearanceFactor', 'FRM_1/gyr_z_sigstats/CrestFactor', 'FRM_1/gyr_z_sigstats/ImpulseFactor', 'FRM_1/gyr_z_sigstats/Kurtosis', 'FRM_1/gyr_z_sigstats/Mean', 'FRM_1/gyr_z_sigstats/PeakValue', 'FRM_1/gyr_z_sigstats/RMS', 'FRM_1/gyr_z_sigstats/ShapeFactor', 'FRM_1/gyr_z_sigstats/Skewness', 'FRM_1/gyr_z_sigstats/Std', 'FRM_1/pwm_1_sigstats/ClearanceFactor', 'FRM_1/pwm_1_sigstats/CrestFactor', 'FRM_1/pwm_1_sigstats/ImpulseFactor', 'FRM_1/pwm_1_sigstats/Kurtosis', 'FRM_1/pwm_1_sigstats/Mean', 'FRM_1/pwm_1_sigstats/PeakValue', 'FRM_1/pwm_1_sigstats/RMS', 'FRM_1/pwm_1_sigstats/ShapeFactor', 'FRM_1/pwm_1_sigstats/Skewness', 'FRM_1/pwm_1_sigstats/Std', 'FRM_1/pwm_2_sigstats/ClearanceFactor', 'FRM_1/pwm_2_sigstats/CrestFactor', 'FRM_1/pwm_2_sigstats/ImpulseFactor', 'FRM_1/pwm_2_sigstats/Kurtosis', 'FRM_1/pwm_2_sigstats/Mean', 'FRM_1/pwm_2_sigstats/PeakValue', 'FRM_1/pwm_2_sigstats/RMS', 'FRM_1/pwm_2_sigstats/ShapeFactor', 'FRM_1/pwm_2_sigstats/Skewness', 'FRM_1/pwm_2_sigstats/Std', 'FRM_1/pwm_3_sigstats/ClearanceFactor', 'FRM_1/pwm_3_sigstats/CrestFactor', 'FRM_1/pwm_3_sigstats/ImpulseFactor', 'FRM_1/pwm_3_sigstats/Kurtosis', 'FRM_1/pwm_3_sigstats/Mean', 'FRM_1/pwm_3_sigstats/PeakValue', 'FRM_1/pwm_3_sigstats/RMS', 'FRM_1/pwm_3_sigstats/ShapeFactor', 'FRM_1/pwm_3_sigstats/Skewness', 'FRM_1/pwm_3_sigstats/Std', 'FRM_1/pwm_4_sigstats/ClearanceFactor', 'FRM_1/pwm_4_sigstats/CrestFactor', 'FRM_1/pwm_4_sigstats/ImpulseFactor', 'FRM_1/pwm_4_sigstats/Kurtosis', 'FRM_1/pwm_4_sigstats/Mean', 'FRM_1/pwm_4_sigstats/PeakValue', 'FRM_1/pwm_4_sigstats/RMS', 'FRM_1/pwm_4_sigstats/ShapeFactor', 'FRM_1/pwm_4_sigstats/Skewness', 'FRM_1/pwm_4_sigstats/Std', 'FRM_1/pwm_5_sigstats/ClearanceFactor', 'FRM_1/pwm_5_sigstats/CrestFactor', 'FRM_1/pwm_5_sigstats/ImpulseFactor', 'FRM_1/pwm_5_sigstats/Kurtosis', 'FRM_1/pwm_5_sigstats/Mean', 'FRM_1/pwm_5_sigstats/PeakValue', 'FRM_1/pwm_5_sigstats/RMS', 'FRM_1/pwm_5_sigstats/ShapeFactor', 'FRM_1/pwm_5_sigstats/Skewness', 'FRM_1/pwm_5_sigstats/Std', 'FRM_1/pwm_6_sigstats/ClearanceFactor', 'FRM_1/pwm_6_sigstats/CrestFactor', 'FRM_1/pwm_6_sigstats/ImpulseFactor', 'FRM_1/pwm_6_sigstats/Kurtosis', 'FRM_1/pwm_6_sigstats/Mean', 'FRM_1/pwm_6_sigstats/PeakValue', 'FRM_1/pwm_6_sigstats/RMS', 'FRM_1/pwm_6_sigstats/ShapeFactor', 'FRM_1/pwm_6_sigstats/Skewness', 'FRM_1/pwm_6_sigstats/Std', 'FRM_1/roll_sigstats/ClearanceFactor', 'FRM_1/roll_sigstats/CrestFactor', 'FRM_1/roll_sigstats/ImpulseFactor', 'FRM_1/roll_sigstats/Kurtosis', 'FRM_1/roll_sigstats/Mean', 'FRM_1/roll_sigstats/PeakValue', 'FRM_1/roll_sigstats/RMS', 'FRM_1/roll_sigstats/ShapeFactor', 'FRM_1/roll_sigstats/Skewness', 'FRM_1/roll_sigstats/Std', 'FRM_1/pitch_sigstats/ClearanceFactor', 'FRM_1/pitch_sigstats/CrestFactor', 'FRM_1/pitch_sigstats/ImpulseFactor', 'FRM_1/pitch_sigstats/Kurtosis', 'FRM_1/pitch_sigstats/Mean', 'FRM_1/pitch_sigstats/PeakValue', 'FRM_1/pitch_sigstats/RMS', 'FRM_1/pitch_sigstats/ShapeFactor', 'FRM_1/pitch_sigstats/Skewness', 'FRM_1/pitch_sigstats/Std', 'FRM_1/yaw_sigstats/ClearanceFactor', 'FRM_1/yaw_sigstats/CrestFactor', 'FRM_1/yaw_sigstats/ImpulseFactor', 'FRM_1/yaw_sigstats/Kurtosis', 'FRM_1/yaw_sigstats/Mean', 'FRM_1/yaw_sigstats/PeakValue', 'FRM_1/yaw_sigstats/RMS', 'FRM_1/yaw_sigstats/ShapeFactor', 'FRM_1/yaw_sigstats/Skewness', 'FRM_1/yaw_sigstats/Std', 'FRM_1/roll_des_sigstats/ClearanceFactor', 'FRM_1/roll_des_sigstats/CrestFactor', 'FRM_1/roll_des_sigstats/ImpulseFactor', 'FRM_1/roll_des_sigstats/Kurtosis', 'FRM_1/roll_des_sigstats/Mean', 'FRM_1/roll_des_sigstats/PeakValue', 'FRM_1/roll_des_sigstats/RMS', 'FRM_1/roll_des_sigstats/ShapeFactor', 'FRM_1/roll_des_sigstats/Skewness', 'FRM_1/roll_des_sigstats/Std', 'FRM_1/pitch_des_sigstats/ClearanceFactor', 'FRM_1/pitch_des_sigstats/CrestFactor', 'FRM_1/pitch_des_sigstats/ImpulseFactor', 'FRM_1/pitch_des_sigstats/Kurtosis', 'FRM_1/pitch_des_sigstats/Mean', 'FRM_1/pitch_des_sigstats/PeakValue', 'FRM_1/pitch_des_sigstats/RMS', 'FRM_1/pitch_des_sigstats/ShapeFactor', 'FRM_1/pitch_des_sigstats/Skewness', 'FRM_1/pitch_des_sigstats/Std', 'FRM_1/yaw_des_sigstats/ClearanceFactor', 'FRM_1/yaw_des_sigstats/CrestFactor', 'FRM_1/yaw_des_sigstats/ImpulseFactor', 'FRM_1/yaw_des_sigstats/Kurtosis', 'FRM_1/yaw_des_sigstats/Mean', 'FRM_1/yaw_des_sigstats/PeakValue', 'FRM_1/yaw_des_sigstats/RMS', 'FRM_1/yaw_des_sigstats/ShapeFactor', 'FRM_1/yaw_des_sigstats/Skewness', 'FRM_1/yaw_des_sigstats/Std', 'FRM_1/vibe_x_sigstats/ClearanceFactor', 'FRM_1/vibe_x_sigstats/CrestFactor', 'FRM_1/vibe_x_sigstats/ImpulseFactor', 'FRM_1/vibe_x_sigstats/Kurtosis', 'FRM_1/vibe_x_sigstats/Mean', 'FRM_1/vibe_x_sigstats/PeakValue', 'FRM_1/vibe_x_sigstats/RMS', 'FRM_1/vibe_x_sigstats/ShapeFactor', 'FRM_1/vibe_x_sigstats/Skewness', 'FRM_1/vibe_x_sigstats/Std', 'FRM_1/vibe_y_sigstats/ClearanceFactor', 'FRM_1/vibe_y_sigstats/CrestFactor', 'FRM_1/vibe_y_sigstats/ImpulseFactor', 'FRM_1/vibe_y_sigstats/Kurtosis', 'FRM_1/vibe_y_sigstats/Mean', 'FRM_1/vibe_y_sigstats/PeakValue', 'FRM_1/vibe_y_sigstats/RMS', 'FRM_1/vibe_y_sigstats/ShapeFactor', 'FRM_1/vibe_y_sigstats/Skewness', 'FRM_1/vibe_y_sigstats/Std', 'FRM_1/vibe_z_sigstats/ClearanceFactor', 'FRM_1/vibe_z_sigstats/CrestFactor', 'FRM_1/vibe_z_sigstats/ImpulseFactor', 'FRM_1/vibe_z_sigstats/Kurtosis', 'FRM_1/vibe_z_sigstats/Mean', 'FRM_1/vibe_z_sigstats/PeakValue', 'FRM_1/vibe_z_sigstats/RMS', 'FRM_1/vibe_z_sigstats/ShapeFactor', 'FRM_1/vibe_z_sigstats/Skewness', 'FRM_1/vibe_z_sigstats/Std', 'FRM_1/acc_x_ps_spec/PeakAmp1', 'FRM_1/acc_x_ps_spec/PeakFreq1', 'FRM_1/acc_x_ps_spec/BandPower', 'FRM_1/acc_y_ps_spec/PeakAmp1', 'FRM_1/acc_y_ps_spec/PeakFreq1', 'FRM_1/acc_y_ps_spec/BandPower', 'FRM_1/acc_z_ps_spec/BandPower', 'FRM_1/gyr_x_ps_spec/PeakAmp1', 'FRM_1/gyr_x_ps_spec/PeakFreq1', 'FRM_1/gyr_x_ps_spec/BandPower', 'FRM_1/gyr_y_ps_spec/PeakAmp1', 'FRM_1/gyr_y_ps_spec/PeakFreq1', 'FRM_1/gyr_y_ps_spec/BandPower', 'FRM_1/gyr_z_ps_spec/BandPower', 'FRM_1/pwm_1_ps_spec/BandPower', 'FRM_1/pwm_2_ps_spec/BandPower', 'FRM_1/pwm_3_ps_spec/BandPower', 'FRM_1/pwm_4_ps_spec/BandPower', 'FRM_1/pwm_5_ps_spec/BandPower', 'FRM_1/pwm_6_ps_spec/BandPower', 'FRM_1/roll_ps_spec/BandPower', 'FRM_1/pitch_ps_spec/BandPower', 'FRM_1/yaw_ps_spec/BandPower', 'FRM_1/roll_des_ps_spec/PeakAmp1', 'FRM_1/roll_des_ps_spec/PeakFreq1', 'FRM_1/roll_des_ps_spec/BandPower', 'FRM_1/pitch_des_ps_spec/PeakAmp1', 'FRM_1/pitch_des_ps_spec/PeakFreq1', 'FRM_1/pitch_des_ps_spec/BandPower', 'FRM_1/yaw_des_ps_spec/BandPower', 'FRM_1/vibe_x_ps_spec/BandPower', 'FRM_1/vibe_y_ps_spec/BandPower', 'FRM_1/vibe_z_ps_spec/BandPower'};
predictors = inputTable(:, predictorNames);
response = inputTable.faultCode_binary;
isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];
classNames = categorical({'0'; '1'});

% Perform cross-validation
KFolds = 5;
cvp = cvpartition(response, 'KFold', KFolds);
% Initialize the predictions to the proper sizes
validationPredictions = response;
numObservations = size(predictors, 1);
numClasses = 2;
validationScores = NaN(numObservations, numClasses);
for fold = 1:KFolds
    trainingPredictors = predictors(cvp.training(fold), :);
    trainingResponse = response(cvp.training(fold), :);
    foldIsCategoricalPredictor = isCategoricalPredictor;

    % Feature Ranking and Selection
    % Replace Inf/-Inf values with NaN to prepare data for normalization
    trainingPredictors = standardizeMissing(trainingPredictors, {Inf, -Inf});
    % Normalize data for feature ranking
    predictorMatrix = normalize(trainingPredictors, "DataVariable", ~foldIsCategoricalPredictor);
    newPredictorMatrix = zeros(size(predictorMatrix));
    for i = 1:size(predictorMatrix, 2)
        if foldIsCategoricalPredictor(i)
            newPredictorMatrix(:,i) = grp2idx(predictorMatrix{:,i});
        else
            newPredictorMatrix(:,i) = predictorMatrix{:,i};
        end
    end
    predictorMatrix = newPredictorMatrix;
    responseVector = grp2idx(trainingResponse);

    % Rank features using ANOVA algorithm
    for i = 1:size(predictorMatrix, 2)
        pValues(i) = anova1(...
            predictorMatrix(:,i), ...
            responseVector, ...
            'off');
    end
    [~,featureIndex] = sort(-log(pValues), 'descend');
    numFeaturesToKeep = 50;
    includedPredictorNames = trainingPredictors.Properties.VariableNames(featureIndex(1:numFeaturesToKeep));
    trainingPredictors = trainingPredictors(:,includedPredictorNames);
    foldIsCategoricalPredictor = foldIsCategoricalPredictor(featureIndex(1:numFeaturesToKeep));

    % Train a classifier
    % This code specifies all the classifier options and trains the classifier.
    template = templateTree(...
        'MaxNumSplits', 20, ...
        'NumVariablesToSample', 'all');
    classificationEnsemble = fitcensemble(...
        trainingPredictors, ...
        trainingResponse, ...
        'Method', 'AdaBoostM1', ...
        'NumLearningCycles', 30, ...
        'Learners', template, ...
        'LearnRate', 0.1, ...
        'ClassNames', classNames);

    % Create the result struct with predict function
    featureSelectionFcn = @(x) x(:,includedPredictorNames);
    ensemblePredictFcn = @(x) predict(classificationEnsemble, x);
    validationPredictFcn = @(x) ensemblePredictFcn(featureSelectionFcn(x));

    % Add additional fields to the result struct

    % Compute validation predictions
    validationPredictors = predictors(cvp.test(fold), :);
    [foldPredictions, foldScores] = validationPredictFcn(validationPredictors);

    % Store predictions in the original order
    validationPredictions(cvp.test(fold), :) = foldPredictions;
    validationScores(cvp.test(fold), :) = foldScores;
end

% Compute validation accuracy
correctPredictions = (validationPredictions == response);
isMissing = ismissing(response);
correctPredictions = correctPredictions(~isMissing);
validationAccuracy = sum(correctPredictions)/length(correctPredictions);
